version: "3.8"

# Services
services:

  # MySQL Service
  mysql:
    image: mysql/mysql-server:8.0
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: demo
    volumes:
      - ./.docker/mysql/my.cnf:/etc/mysql/my.cnf
      - mysqldata:/var/lib/mysql
    command: mysqld --sql_mode=""
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      interval: 5s
      retries: 10

  # PHP Service
  php:
    build: ./.docker/php
    working_dir: /var/www/php
    restart: always
    volumes:
      - ./src:/var/www/php
      - ./.docker/mysql/my.cnf:/etc/mysql/my.cnf
    depends_on:
      mysql:
        condition: service_healthy

  # Nginx Service
  nginx:
    image: nginx:1.21
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/php
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
    links:
      - php

  # PhpMyAdmin Service  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    restart: always
    ports:
      - 8090:80
    environment:
      PMA_HOST: mysql
      UPLOAD_LIMIT: 128M
    depends_on:
      mysql:
        condition: service_healthy

  # Volumes
volumes:
  mysqldata:
